export const mockCustomers = [
  {
    id: "asdaweqe",
    Name: "Cosmo Travels",
    Address: "Doha, Qatar",
    City: "London",
    Postcode: "SW1 1AA",
    Country: "United Kingdom",
    Phone: "+44 (0)20 7123 4567",
    Email: "arshakanjum@gmail.com",
    Website: "www.cosmotravels.com",
  },
  {
    id: "asdasdade",
    Name: "Mini-mart",
    Address: "Doha, Qatar",
    City: "London",
    Postcode: "SW1 1AA",
    Country: "United Kingdom",
    Phone: "+44 (0)20 7123 4567",
    Email: "arshakanjum@gmail.com",
    Website: "www.cosmotravels.com",
  },
  {
    id: "asdadsda",
    Name: "Figma Travels",
    Address: "Doha, Qatar",
    City: "London",
    Postcode: "SW1 1AA",
    Country: "United Kingdom",
    Phone: "+44 (0)20 7123 4567",
    Email: "arshakanjum@gmail.com",
    Website: "www.cosmotravels.com",
  },
  {
    id: "asdaweqe",
    Name: "Cosmo Travels",
    Address: "Doha, Qatar",
    City: "London",
    Postcode: "SW1 1AA",
    Country: "United Kingdom",
    Phone: "+44 (0)20 7123 4567",
    Email: "arshakanjum@gmail.com",
    Website: "www.cosmotravels.com",
  },
  {
    id: "asdasdade",
    Name: "Mini-mart",
    Address: "Doha, Qatar",
    City: "London",
    Postcode: "SW1 1AA",
    Country: "United Kingdom",
    Phone: "+44 (0)20 7123 4567",
    Email: "arshakanjum@gmail.com",
    Website: "www.cosmotravels.com",
  },
  {
    id: "asdadsda",
    Name: "Figma Travels",
    Address: "Doha, Qatar",
    City: "London",
    Postcode: "SW1 1AA",
    Country: "United Kingdom",
    Phone: "+44 (0)20 7123 4567",
    Email: "arshakanjum@gmail.com",
    Website: "www.cosmotravels.com",
  },
];

export const mockProducts = [
  {
    id: "asdaweq4e",
    Name: "AMC",
    Description: "Annual Maintanence Contract",
    Price: "1000",
    Unit: "Year",
  },
  {
    id: "asdaweq2e",
    Name: "Fire Extinguisher",
    Description: "Fire Extinguisher - Red",
    Price: "100",
    Unit: "Pieces",
  },
  {
    id: "asdaweq6e",
    Name: "Smoke Detector Service",
    Description: "Service of Smoke detector",
    Price: "5000",
    Unit: "Unit",
  },
  {
    id: "asdawe3qe",
    Name: "Smoke Detector Fixing",
    Description: "Fixing of Smoke Detector",
    Price: "1000",
    Unit: "Unit",
  },
  {
    id: "asdawe2qe",
    Name: "Annual Maintanence Contract",
    Description: "Annual Maintanence Contract",
    Price: "1000",
    Unit: "Year",
  },
  {
    id: "asdaweq1e",
    Name: "Annual Maintanence Contract",
    Description: "Annual Maintanence Contract",
    Price: "1000",
    Unit: "Year",
  },
];
